from __future__ import annotations

import html
from importlib import resources

from mythings.github import CIStatus

from mydashboard.fleet import RepoStatus

_CI_BADGE = {
    CIStatus.SUCCESS: "✅",
    CIStatus.FAILURE: "❌",
    CIStatus.PENDING: "⏳",
    CIStatus.NONE: "—",
}

_CI_PILL = {
    CIStatus.SUCCESS: ("good", "✓ CI"),
    CIStatus.FAILURE: ("crit", "✗ CI"),
    CIStatus.PENDING: ("warn", "⏳ CI"),
    CIStatus.NONE: ("", "— CI"),
}

_CI_SORT_RANK = {
    CIStatus.FAILURE: 0,
    CIStatus.PENDING: 1,
    CIStatus.NONE: 2,
    CIStatus.SUCCESS: 3,
}

_STALE_DAYS = 30
_VERY_STALE_DAYS = 90

_STYLE = resources.files("mydashboard").joinpath("dashboard.css").read_text(encoding="utf-8")

_FOOTER = (
    "Generated by <code>mydashboard render</code> — published via PR to the docs site, never\n"
    "merged by the tool. The banner is the tool's single Engine call\n"
    "(<code>--summarize</code>); everything else on this page is deterministic."
)


def _row(status: RepoStatus) -> str:
    purpose = status.purpose or "_(no purpose seam found)_"
    activity = status.last_dev_ledger or status.last_ledger or "—"
    return (
        f"| [{status.name}](https://github.com/{status.slug}) | {purpose} | "
        f"{_CI_BADGE[status.ci]} | {status.open_issues} | {status.open_prs} | {activity} |"
    )


def _table(statuses: list[RepoStatus]) -> str:
    header = "| Tool | Purpose | CI | Issues | PRs | Last activity |\n"
    header += "| --- | --- | --- | --- | --- | --- |\n"
    return header + "\n".join(_row(status) for status in statuses)


def render_org_table(shelved: dict[str, list[RepoStatus]]) -> str:
    parts = [
        f"## {label}\n\n{_table(statuses)}" for label, statuses in shelved.items() if statuses
    ]
    return "\n\n".join(parts) + "\n"


def _pill(text: str, tone: str = "") -> str:
    cls = f"pill {tone}".strip()
    return f'<span class="{cls}">{html.escape(text)}</span>'


def _card(status: RepoStatus, *, unshelved: bool = False) -> str:
    tone, ci_label = _CI_PILL[status.ci]
    pills = [
        _pill(ci_label, tone),
        _pill(f"{status.open_prs} PR", "warn" if status.open_prs else ""),
        _pill(f"{status.open_issues} issue" + ("" if status.open_issues == 1 else "s")),
    ]
    if status.last_activity_days is not None and status.last_activity_days >= _STALE_DAYS:
        stale_tone = "crit" if status.last_activity_days >= _VERY_STALE_DAYS else "warn"
        pills.append(_pill(f"stale {status.last_activity_days}d", stale_tone))
    if unshelved:
        pills.append(_pill("⚠ not in shelves.toml", "warn"))
    purpose = html.escape(status.purpose) if status.purpose else "(no purpose seam found)"
    activity = status.last_dev_ledger or status.last_ledger
    last = f'\n        <div class="last">{html.escape(activity)}</div>' if activity else ""
    url = f"https://github.com/{html.escape(status.slug)}"
    return f"""\
      <div class="tool">
        <div class="name"><a href="{url}">{html.escape(status.name)}</a></div>
        <p class="purpose">{purpose}</p>
        <div class="pills">{"".join(pills)}</div>{last}
      </div>"""


def _sort_key(status: RepoStatus) -> tuple[int, int, str]:
    days = status.last_activity_days
    staleness_rank = -days if days is not None else 1
    return (_CI_SORT_RANK[status.ci], staleness_rank, status.name)


def _shelf(
    label: str, statuses: list[RepoStatus], *, what: str | None = None, unshelved: bool = False
) -> str:
    statuses = sorted(statuses, key=_sort_key)
    count = f"{len(statuses)} tool" + ("" if len(statuses) == 1 else "s")
    what_span = f'\n      <span class="what">{html.escape(what)}</span>' if what else ""
    callout = (
        '\n    <p class="callout">⚠ Drift made visible, not silent: a new repo lands here '
        "until it is classified in shelves.toml.</p>"
        if unshelved
        else ""
    )
    cards = "\n".join(_card(status, unshelved=unshelved) for status in statuses)
    cls = "shelf unshelved" if unshelved else "shelf"
    return f"""\
  <section class="{cls}">
    <div class="shelf-head">
      <h2>{html.escape(label)}</h2><span class="count">{count}</span>{what_span}
    </div>{callout}
    <div class="grid">
{cards}
    </div>
  </section>"""


def _tile(k: str, v: str, d: str) -> str:
    return (
        f'    <div class="tile"><div class="k">{k}</div>'
        f'<div class="v">{v}</div><div class="d">{d}</div></div>'
    )


def _tiles(shelved: dict[str, list[RepoStatus]], unshelved: list[RepoStatus]) -> str:
    statuses = [s for group in shelved.values() for s in group] + unshelved
    shelf_count = sum(1 for group in shelved.values() if group)
    green = sum(1 for s in statuses if s.ci is CIStatus.SUCCESS)
    ci_parts = []
    for state, word in (
        (CIStatus.FAILURE, "failing"),
        (CIStatus.PENDING, "pending"),
        (CIStatus.NONE, "no CI"),
    ):
        n = sum(1 for s in statuses if s.ci is state)
        if n:
            ci_parts.append(f"{n} {word}")
    ci_detail = " · ".join(ci_parts) if ci_parts else "all green"
    tiles = "\n".join(
        [
            _tile("Repos", str(len(statuses)), f"across {shelf_count} shelves"),
            _tile(
                "CI on main",
                f'{green}<span class="unit">/{len(statuses)}</span>',
                ci_detail,
            ),
            _tile("Open PRs", str(sum(s.open_prs for s in statuses)), "across the fleet"),
            _tile("Open issues", str(sum(s.open_issues for s in statuses)), "across the backlog"),
        ]
    )
    return f'  <div class="tiles">\n{tiles}\n  </div>'


def render_org_page(
    shelved: dict[str, list[RepoStatus]],
    unshelved: list[RepoStatus],
    *,
    banner: str | None = None,
    taglines: dict[str, str] | None = None,
    generated_at: str | None = None,
) -> str:
    taglines = taglines or {}
    total = sum(len(group) for group in shelved.values()) + len(unshelved)
    banner_html = (
        f'\n    <p class="banner"><strong>State of the fleet:</strong> {html.escape(banner)}</p>'
        if banner
        else ""
    )
    sections = [
        _shelf(label, statuses, what=taglines.get(label))
        for label, statuses in shelved.items()
        if statuses
    ]
    if unshelved:
        sections.append(_shelf("Unshelved", unshelved, unshelved=True))
    body = "\n\n".join(sections)
    generated_html = (
        f'\n    <p class="generated">Generated {html.escape(generated_at)}</p>'
        if generated_at
        else ""
    )
    return f"""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>MyThingsLab — Fleet Dashboard</title>
<style>
{_STYLE}</style>
</head>
<body>
<main>
  <header class="masthead">
    <div class="eyebrow">MyThingsLab · fleet dashboard</div>
    <h1>{total} tools, one loop</h1>{banner_html}
  </header>

{_tiles(shelved, unshelved)}

{body}

  <footer>
    {_FOOTER}{generated_html}
  </footer>
</main>
</body>
</html>
"""


def render_repo_card(status: RepoStatus) -> str:
    lines = [
        f"# {status.name}",
        "",
        f"Purpose: {status.purpose or '_(no purpose seam found)_'}",
        f"CI (main): {_CI_BADGE[status.ci]}",
        f"Open issues: {status.open_issues}",
        f"Open PRs: {status.open_prs}",
    ]
    if status.last_dev_ledger:
        lines.append(f"Last dev-ledger: {status.last_dev_ledger}")
    if status.last_ledger:
        lines.append(f"Last ledger activity: {status.last_ledger}")
    return "\n".join(lines) + "\n"
